homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.4622589
  longitude: 0.003979
  #latitude: 51.4833
  #longitude: -0.0334
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

#customize: !include_dir_merge_named customisations

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# hass.io
hassio:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: gollo.duckdns.org
  trusted_networks: 
    - 192.168.0.0/24
    - 127.0.0.1
    - ::1

# Checks for available updates
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: warn
  logs:
    homeassistant.components.hassio: debug

# Track the sun
sun:

# IFTTT
ifttt:
  key: !secret ifttt_key

# Weather Prediction
sensor:
  - platform: plex
    host: 192.168.0.11
    port: 32400
    username: !secret sensor_plex_username
    password: !secret sensor_plex_password
  - platform: metoffice
    api_key: !secret sensor_metoffice_api_key
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - uv
      - precipitation
      - humidity
  - platform: random
  - platform: speedtest
    minute:
      - 0
      - 15
      - 30
      - 45
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: pi_hole
    host: 192.168.0.3
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today 
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_free
    - type: swap_use
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
#    - type: process
#      arg: "/usr/bin/python3 -m homeassistant --config /config"


# Text to speech
tts:
  platform: google

group: !include groups.yaml

media_player:
  - name: firestick-kodi
    platform: kodi
    host: 192.168.0.144
  - name: firetv-kodi
    platform: kodi
    host: 192.168.0.145
#  - name: firestick
#    platform: firetv
#    device: firetvstick
  - name: firetv
    platform: firetv
    device: firetv

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mqtt:
  broker: 192.168.0.190
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks
# - platform: bluetooth_tracker
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 30
         
zone:
  name: Home
  latitude: 51.4622589
  longitude: 0.003979
  radius: 150

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - '22152713'
weather:
  - platform: metoffice
    api_key: !secret sensor_metoffice_api_key
#camera:
#  - platform: rpi_camera
#    name: raspberry
#    file_path: /tmp/touched.jpg
  

#camera:
#  - platform: mjpeg
#    name: Front Room
#    mjpeg_url: http://192.168.0.196/videostream.cgi
#    username: admin
#    password: !secret camera_mjpeg_password mDaO2203
#  - platform: mjpeg
#    name: Back Yard
#    mjpeg_url: http://192.168.0.170/videostream.cgi
#    username: admin
#    password: !secret camera_mjpeg_password

    
automation: !include automations.yaml

#automation old:
#  - alias: Check sensor value and Telegram 
#    trigger:
#      platform: numeric_state
#      entity_id: sensor.random_sensor
#      above: 10
#    action:
#      - service: persistent_notification.create
#        data:
#          message: "Sensor value greater than 10"
#      - service: telegram_bot.send_message
#        data:
#          message: "Fucking gaylord"
#      - service: tts.google_say
#        entity_id: media_player.living_room_home
#        data:
#          message: 'May the Force be with you.'
#
#  - alias: Turn on light when sun sets
#    initial_state: True
#    hide_entity: False
#    trigger:
#      platform: sun
#      event: sunset
#    action:
#      service: light.turn_on

notify:
  - platform: nfandroidtv
    name: firetv
    host: 192.168.0.145
  - platform: nfandroidtv
    name: firetvstick
    host: 192.168.0.144

#light:
#  - platform: tplink
#    host: 192.168.0.112

switch:
  - platform: tplink
    host: 192.168.0.161

binary_sensor:
  - platform: ping
    host: 192.168.0.1
