homeassistant:
  #customize_glob:
  #  light.*:
  #    custom_ui_state_card: custom-ui
  #  cover.*:
  #    custom_ui_state_card: custom-ui
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.4622589
  longitude: 0.003979
  #latitude: 51.4833
  #longitude: -0.0334
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# hass.io
hassio:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: gollo.duckdns.org
  trusted_networks: 
    - 192.168.0.0/24
    - 127.0.0.1
    - ::1

# Checks for available updates
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: warn
  logs:
    homeassistant.components.hassio: debug
    requests.packages.urllib3: critical
    homeassistant.components.camera.mjpeg: critical

# Track the sun
sun:

# IFTTT
ifttt:
  key: !secret ifttt_key

sensor:
#  - platform: dht
#    sensor: DHT22
#    pin: 23
#    monitored_conditions:
#      - temperature
#      - humidity
  - platform: london_air
    locations:
      - Lewisham
#  - platform: uk_transport
#    app_id: !secret uk_transport_app_id:
#    app_key: !secret aaffb8f1a9aeb35abbaab931bbc40b4f
#    queries:
#      - mode: train
#        origin: BKH
#        destination: LBG
#      - mode: bus
#        origin: 490005918E
#        destination: 'P R Hospital'
#  - platform: london_underground
#    line:
#      - Northern
  - platform: plex
    host: 192.168.0.11
    port: 32400
    username: !secret sensor_plex_username
    password: !secret sensor_plex_password
  - platform: metoffice
    api_key: !secret sensor_metoffice_api_key
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - visibility_distance
      - uv
      - precipitation
      - humidity
#  - platform: random
  - platform: speedtest
    minute:
      - 0
      - 15
      - 30
      - 45
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: pi_hole
    host: 192.168.0.3
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today 
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_free
    - type: swap_use
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
#    - type: process
#      arg: "/usr/bin/python3 -m homeassistant --config /config"


# Text to speech
tts:
  platform: google

media_player:
  - name: firestick-kodi
    platform: kodi
    host: 192.168.0.144
  - name: firetv-kodi
    platform: kodi
    host: 192.168.0.145
  - name: firestick
    platform: firetv
    device: firetvstick
  - name: firetv
    platform: firetv
    device: firetv
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: true

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#mqtt:
#  broker: 192.168.0.190
#  port: 1883
#  client_id: !secret mqtt_client_id
#  username: !secret mqtt_username
#  password: !secret mqtt_password

device_tracker:
#  - platform: owntracks
# - platform: bluetooth_tracker
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 30
         
zone:
  name: Home
  latitude: 51.4622589
  longitude: 0.003979
  radius: 150

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - '22152713'
weather:
  - platform: metoffice
    api_key: !secret sensor_metoffice_api_key
#camera:
#  - platform: rpi_camera
#    name: raspberry
#    file_path: /tmp/touched.jpg
  

camera:
  - platform: mjpeg
    name: Front Room
    mjpeg_url: http://192.168.0.196/videostream.cgi
    username: admin
    password: !secret camera_mjpeg_password
  - platform: mjpeg
    name: Back Yard
    mjpeg_url: http://192.168.0.170/videostream.cgi
    username: admin
    password: !secret camera_mjpeg_password

    
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml

notify:
  - platform: nfandroidtv
    name: firetv
    host: 192.168.0.145
  - platform: nfandroidtv
    name: firetvstick
    host: 192.168.0.144
  - platform: html5
    name: push
    gcm_api_key: !secret html5_gcm_api_key
    gcm_sender_id: !secret html5_gcm_sender_id


light:
  - platform: tplink
    host: 192.168.0.112

switch:
  - platform: tplink
    host: 192.168.0.161

binary_sensor:
  - platform: ping
    host: 192.168.0.1

# Define input_slider
#input_slider:
#  downstairs_brightness:
#    name: Brightness
#    initial: 255
#    min: 0
#    max: 255
#    step: 1

climate:
  - platform: nest

prometheus:

panel_iframe:
  terminal:
    title: Terminal
    icon: mdi:console
    url: http://192.168.0.190:7681
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.0.190:3218

hdmi_cec:
  platform: media_player
  devices:
    TV: 0.0.0.0
    Chromecast: 4.0.0.0
    FireTV: 3.0.0.0

